exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('appointments')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('appointments').insert([
        {
          id: 1,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 2,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 3,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 4,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 5,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 6,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 7,
          name: '',
          phone_number: '',
          time: '7',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 8,
          name: '',
          phone_number: '',
          time: '8',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 9,
          name: '',
          phone_number: '',
          time: '9',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 10,
          name: '',
          phone_number: '',
          time: '10',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 11,
          name: '',
          phone_number: '',
          time: '11',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 12,
          name: '',
          phone_number: '',
          time: '08',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 13,
          name: '',
          phone_number: '',
          time: '09',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 14,
          name: '',
          phone_number: '',
          time: '010',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 15,
          name: '',
          phone_number: '',
          time: '011',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 16,
          name: '',
          phone_number: '',
          time: '012',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 17,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 18,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 19,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 20,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 21,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 22,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 23,
          name: '',
          phone_number: '',
          time: '08',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 24,
          name: '',
          phone_number: '',
          time: '09',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 25,
          name: '',
          phone_number: '',
          time: '010',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 26,
          name: '',
          phone_number: '',
          time: '011',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 27,
          name: '',
          phone_number: '',
          time: '012',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 28,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 29,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 30,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 31,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 32,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 33,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 1
        },
        {
          id: 34,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 35,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 36,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 37,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 38,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 39,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 40,
          name: '',
          phone_number: '',
          time: '7',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 41,
          name: '',
          phone_number: '',
          time: '8',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 42,
          name: '',
          phone_number: '',
          time: '9',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 43,
          name: '',
          phone_number: '',
          time: '10',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 44,
          name: '',
          phone_number: '',
          time: '11',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 45,
          name: '',
          phone_number: '',
          time: '08',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 46,
          name: '',
          phone_number: '',
          time: '09',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 47,
          name: '',
          phone_number: '',
          time: '010',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 48,
          name: '',
          phone_number: '',
          time: '011',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 49,
          name: '',
          phone_number: '',
          time: '012',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 50,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 51,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 52,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 53,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 54,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 55,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 56,
          name: '',
          phone_number: '',
          time: '08',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 57,
          name: '',
          phone_number: '',
          time: '09',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 58,
          name: '',
          phone_number: '',
          time: '010',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 59,
          name: '',
          phone_number: '',
          time: '011',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 60,
          name: '',
          phone_number: '',
          time: '012',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 61,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 62,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 63,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 64,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 65,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 66,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 2
        },
        {
          id: 67,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 68,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 69,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 70,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 71,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 72,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 73,
          name: '',
          phone_number: '',
          time: '7',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 74,
          name: '',
          phone_number: '',
          time: '8',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 75,
          name: '',
          phone_number: '',
          time: '9',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 76,
          name: '',
          phone_number: '',
          time: '10',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 77,
          name: '',
          phone_number: '',
          time: '11',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 78,
          name: '',
          phone_number: '',
          time: '08',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 79,
          name: '',
          phone_number: '',
          time: '09',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 80,
          name: '',
          phone_number: '',
          time: '010',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 81,
          name: '',
          phone_number: '',
          time: '011',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 82,
          name: '',
          phone_number: '',
          time: '012',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 83,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 84,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 85,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 86,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 87,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 88,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 89,
          name: '',
          phone_number: '',
          time: '08',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 90,
          name: '',
          phone_number: '',
          time: '09',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 91,
          name: '',
          phone_number: '',
          time: '010',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 92,
          name: '',
          phone_number: '',
          time: '011',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 93,
          name: '',
          phone_number: '',
          time: '012',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 94,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 95,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 96,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 97,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 98,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 99,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 3
        },
        {
          id: 100,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 101,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 102,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 103,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 104,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 105,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 106,
          name: '',
          phone_number: '',
          time: '7',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 107,
          name: '',
          phone_number: '',
          time: '8',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 108,
          name: '',
          phone_number: '',
          time: '9',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 109,
          name: '',
          phone_number: '',
          time: '10',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 110,
          name: '',
          phone_number: '',
          time: '11',
          date: '',
          person: 'jimmy',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 111,
          name: '',
          phone_number: '',
          time: '08',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 112,
          name: '',
          phone_number: '',
          time: '09',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 113,
          name: '',
          phone_number: '',
          time: '010',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 114,
          name: '',
          phone_number: '',
          time: '011',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 115,
          name: '',
          phone_number: '',
          time: '012',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 116,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 117,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 118,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 119,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 120,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 121,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'bernice',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 122,
          name: '',
          phone_number: '',
          time: '08',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 123,
          name: '',
          phone_number: '',
          time: '09',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 124,
          name: '',
          phone_number: '',
          time: '010',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 125,
          name: '',
          phone_number: '',
          time: '011',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 126,
          name: '',
          phone_number: '',
          time: '012',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 127,
          name: '',
          phone_number: '',
          time: '1',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 128,
          name: '',
          phone_number: '',
          time: '2',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 129,
          name: '',
          phone_number: '',
          time: '3',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 130,
          name: '',
          phone_number: '',
          time: '4',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 131,
          name: '',
          phone_number: '',
          time: '5',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 4
        },
        {
          id: 132,
          name: '',
          phone_number: '',
          time: '6',
          date: '',
          person: 'walkin',
          subject: '',
          note: '',
          date_id: 4
        }
      ]);
    });
};
